import Navbar from "../../../include/Navbar";
import logo from "../../../assets/Logo.jpg";
function SeamlessPipe() {
    return (
        <>
            <Navbar />
            <div className="container">
                <div className="row mt-3">
                    <div className="col-md-2">
                        <img src={logo} alt="" style={{ width: '100px', height: '100px' }} />
                    </div>
                    <div className="col-md-10">
                        <div className="container">
                            <h3>lorem ipsum</h3>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo ducimus, ea animi earum illo pariatur, voluptatibus magni commodi, nam nemo id itaque cum in sed error provident officia incidunt debitis!
                        </div>
                    </div>
                </div>

                <div className="row mt-4 text-center mb-3">
                    <h3>SEAMLESS LINEPIPE ASTM-A-106 Gr. B. DIMENSION</h3>
                    <div className="card shadow-lg rounded">
                        <div className="card-body">
                            <div className="table-responsive">
                                <table
                                    className="table text-center table-bordered table-striped table-hover font-weight-bold"
                                >
                                    <thead>
                                        <tr>
                                            <th>Nominal Pipe Size (Inch)</th>
                                            <th>Outside Diameter (mm)</th>
                                            <th>Schedule 10 (mm)</th>
                                            <th>Schedule 20 (mm)</th>
                                            <th>Schedule 30 (mm)</th>
                                            <th>Standard W/T (mm)</th>
                                            <th>Schedule 40 (mm)</th>
                                            <th>Extra Strong (mm)</th>
                                            <th>Schedule 60 (mm)</th>
                                            <th>Schedule 80 (mm)</th>
                                            <th>Schedule 100 (mm)</th>
                                            <th>Schedule 120 (mm)</th>
                                            <th>Schedule 140 (mm)</th>
                                            <th>Schedule 160 (mm)</th>
                                            <th>Double Extra Strong (mm)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1/4</td>
                                            <td>13.7</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>2.24</td>
                                            <td>2.24</td>
                                            <td>3.02</td>
                                            <td></td>
                                            <td>3.02</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>3/8</td>
                                            <td>17.1</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>2.31</td>
                                            <td>2.31</td>
                                            <td>3.20</td>
                                            <td></td>
                                            <td>3.20</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>1/2</td>
                                            <td>21.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>2.77</td>
                                            <td>2.77</td>
                                            <td>3.73</td>
                                            <td></td>
                                            <td>3.73</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>4.78</td>
                                            <td>7.47</td>
                                        </tr>
                                        <tr>
                                            <td>3/4</td>
                                            <td>26.7</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>2.87</td>
                                            <td>2.87</td>
                                            <td>3.91</td>
                                            <td></td>
                                            <td>3.91</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>5.56</td>
                                            <td>7.82</td>
                                        </tr>
                                        <tr>
                                            <td>1</td>
                                            <td>33.4</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>3.38</td>
                                            <td>3.38</td>
                                            <td>4.55</td>
                                            <td></td>
                                            <td>4.55</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>6.35</td>
                                            <td>9.09</td>
                                        </tr>
                                        <tr>
                                            <td>11/4</td>
                                            <td>42.2</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>3.56</td>
                                            <td>3.56</td>
                                            <td>4.85</td>
                                            <td></td>
                                            <td>4.85</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>6.35</td>
                                            <td>9.70</td>
                                        </tr>
                                        <tr>
                                            <td>11/2</td>
                                            <td>48.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>3.68</td>
                                            <td>3.68</td>
                                            <td>5.08</td>
                                            <td></td>
                                            <td>5.08</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>7.14</td>
                                            <td>10.15</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>60.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>3.91</td>
                                            <td>3.91</td>
                                            <td>5.54</td>
                                            <td></td>
                                            <td>5.54</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>8.74</td>
                                            <td>11.07</td>
                                        </tr>
                                        <tr>
                                            <td>21/3</td>
                                            <td>73.0</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>5.16</td>
                                            <td>5.16</td>
                                            <td>7.01</td>
                                            <td></td>
                                            <td>7.01</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>9.53</td>
                                            <td>14.02</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>88.9</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>5.49</td>
                                            <td>5.49</td>
                                            <td>7.62</td>
                                            <td></td>
                                            <td>7.62</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>11.13</td>
                                            <td>15.24</td>
                                        </tr>
                                        <tr>
                                            <td>31/2</td>
                                            <td>101.6</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>5.74</td>
                                            <td>5.74</td>
                                            <td>8.08</td>
                                            <td></td>
                                            <td>8.08</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>-</td>
                                            <td>-</td>
                                        </tr>
                                        <tr>
                                            <td>4</td>
                                            <td>114.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>6.02</td>
                                            <td>6.02</td>
                                            <td>8.56</td>
                                            <td></td>
                                            <td>8.56</td>
                                            <td></td>
                                            <td>11.13</td>
                                            <td></td>
                                            <td>13.49</td>
                                            <td>17.12</td>
                                        </tr>
                                        <tr>
                                            <td>5</td>
                                            <td>141.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>6.55</td>
                                            <td>6.55</td>
                                            <td>9.53</td>
                                            <td></td>
                                            <td>9.53</td>
                                            <td></td>
                                            <td>12.70</td>
                                            <td></td>
                                            <td>15.88</td>
                                            <td>19.05</td>
                                        </tr>
                                        <tr>
                                            <td>6</td>
                                            <td>168.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>7.11</td>
                                            <td>7.11</td>
                                            <td>10.97</td>
                                            <td></td>
                                            <td>10.97</td>
                                            <td></td>
                                            <td>14.27</td>
                                            <td></td>
                                            <td>18.26</td>
                                            <td>21.95</td>
                                        </tr>
                                        <tr>
                                            <td>8</td>
                                            <td>219.1</td>
                                            <td></td>
                                            <td>6.35</td>
                                            <td>7.04</td>
                                            <td>8.18</td>
                                            <td>8.18</td>
                                            <td>12.70</td>
                                            <td>1031</td>
                                            <td>12.70</td>
                                            <td>15.09</td>
                                            <td>18.26</td>
                                            <td>20.52</td>
                                            <td>23.01</td>
                                            <td>22.23</td>
                                        </tr>
                                        <tr>
                                            <td>10</td>
                                            <td>273.1</td>
                                            <td></td>
                                            <td>6.35</td>
                                            <td>7.80</td>
                                            <td>9.27</td>
                                            <td>9.27</td>
                                            <td>12.70</td>
                                            <td>12.70</td>
                                            <td>15.09</td>
                                            <td>18.26</td>
                                            <td>21.44</td>
                                            <td>25.40</td>
                                            <td>28.58</td>
                                            <td>25.40</td>
                                        </tr>
                                        <tr>
                                            <td>12</td>
                                            <td>323.9</td>
                                            <td></td>
                                            <td>6.35</td>
                                            <td>8.38</td>
                                            <td>9.53</td>
                                            <td>10.31</td>
                                            <td>12.70</td>
                                            <td>14.27</td>
                                            <td>17.48</td>
                                            <td>21.44</td>
                                            <td>25.40</td>
                                            <td>28.58</td>
                                            <td>33.32</td>
                                            <td>25.40</td>
                                        </tr>
                                        <tr>
                                            <td>14</td>
                                            <td>355.6</td>
                                            <td>6.35</td>
                                            <td>7.92</td>
                                            <td>9.53</td>
                                            <td>9.53</td>
                                            <td>11.13</td>
                                            <td>12.70</td>
                                            <td>15.09</td>
                                            <td>19.05</td>
                                            <td>23.83</td>
                                            <td>27.79</td>
                                            <td>31.75</td>
                                            <td>35.71</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>16</td>
                                            <td>406.4</td>
                                            <td>6.35</td>
                                            <td>7.92</td>
                                            <td>9.53</td>
                                            <td>9.53</td>
                                            <td>12.70</td>
                                            <td>12.70</td>
                                            <td>16.66</td>
                                            <td>21.44</td>
                                            <td>26.19</td>
                                            <td>30.96</td>
                                            <td>36.53</td>
                                            <td>40.49</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>18</td>
                                            <td>457.0</td>
                                            <td>6.35</td>
                                            <td>7.92</td>
                                            <td>11.13</td>
                                            <td>9.53</td>
                                            <td>14.27</td>
                                            <td>12.70</td>
                                            <td>19.05</td>
                                            <td>23.88</td>
                                            <td>29.36</td>
                                            <td>34.93</td>
                                            <td>39.67</td>
                                            <td>45.24</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>20</td>
                                            <td>508</td>
                                            <td>6.35</td>
                                            <td>9.53</td>
                                            <td>12.70</td>
                                            <td>9.53</td>
                                            <td>15.09</td>
                                            <td>12.70</td>
                                            <td>20.62</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>22</td>
                                            <td>559</td>
                                            <td>6.35</td>
                                            <td>9.53</td>
                                            <td>12.70</td>
                                            <td>9.53</td>
                                            <td>-</td>
                                            <td>12.70</td>
                                            <td>22.23</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>24</td>
                                            <td>610</td>
                                            <td>6.35</td>
                                            <td>9.53</td>
                                            <td>14.27</td>
                                            <td>9.53</td>
                                            <td>17.48</td>
                                            <td>12.70</td>
                                            <td>24.61</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>26</td>
                                            <td>660</td>
                                            <td>7.92</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td>9.53</td>
                                            <td>-</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>28</td>
                                            <td>711</td>
                                            <td>7.92</td>
                                            <td>12.70</td>
                                            <td>15.88</td>
                                            <td>9.53</td>
                                            <td>-</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>30</td>
                                            <td>762</td>
                                            <td>7.92</td>
                                            <td>12.70</td>
                                            <td>15.88</td>
                                            <td>9.53</td>
                                            <td>-</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>32</td>
                                            <td>813</td>
                                            <td>7.92</td>
                                            <td>12.70</td>
                                            <td>15.88</td>
                                            <td>9.53</td>
                                            <td>17.48</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>34</td>
                                            <td>864</td>
                                            <td>7.92</td>
                                            <td>12.70</td>
                                            <td>15.88</td>
                                            <td>9.53</td>
                                            <td>17.48</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>36</td>
                                            <td>914</td>
                                            <td>7.92</td>
                                            <td>12.70</td>
                                            <td>15.88</td>
                                            <td>9.53</td>
                                            <td>19.05</td>
                                            <td>12.70</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>

                <div className="row mt-5 text-center mb-3">
                    <h3>SEAMLESS LINEPIPE ASTM-A-106 Gr. B. WEIGHTS</h3>
                    <div className="card shadow-lg rounded">
                        <div className="card-body">
                            <div className="table-responsive">
                                <table
                                    className="table text-center table-bordered table-striped table-hover font-weight-bold"
                                >
                                    <thead>
                                        <tr>
                                            <th>Nominal Pipe Size (Inch)</th>
                                            <th>Outside Diameter (mm)</th>
                                            <th>Schedule 10 (mm)</th>
                                            <th>Schedule 20 (mm)</th>
                                            <th>Schedule 30 (mm)</th>
                                            <th>Standard W/T (mm)</th>
                                            <th>Schedule 40 (mm)</th>
                                            <th>Extra Strong (mm)</th>
                                            <th>Schedule 60 (mm)</th>
                                            <th>Schedule 80 (mm)</th>
                                            <th>Schedule 100 (mm)</th>
                                            <th>Schedule 120 (mm)</th>
                                            <th>Schedule 140 (mm)</th>
                                            <th>Schedule 160 (mm)</th>
                                            <th>Double Extra Strong (mm)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1/4</td>
                                            <td>13.7</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>0.63</td>
                                            <td>0.63</td>
                                            <td>0.80</td>
                                            <td></td>
                                            <td>0.80</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>3/8</td>
                                            <td>17.1</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>0.83</td>
                                            <td>0.83</td>
                                            <td>1.10</td>
                                            <td></td>
                                            <td>1.10</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>1/2</td>
                                            <td>21.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>1.27</td>
                                            <td>1.27</td>
                                            <td>1.62</td>
                                            <td></td>
                                            <td>1.62</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>1.95</td>
                                            <td>2.55</td>
                                        </tr>
                                        <tr>
                                            <td>3/4</td>
                                            <td>26.7</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>1.69</td>
                                            <td>1.69</td>
                                            <td>2.20</td>
                                            <td></td>
                                            <td>2.20</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>2.90</td>
                                            <td>3.64</td>
                                        </tr>
                                        <tr>
                                            <td>1</td>
                                            <td>33.4</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>2.50</td>
                                            <td>2.50</td>
                                            <td>3.24</td>
                                            <td></td>
                                            <td>3.24</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>4.24</td>
                                            <td>5.45</td>
                                        </tr>
                                        <tr>
                                            <td>11/4</td>
                                            <td>42.2</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>3.39</td>
                                            <td>3.39</td>
                                            <td>4.47</td>
                                            <td></td>
                                            <td>4.47</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>5.61</td>
                                            <td>7.77</td>
                                        </tr>
                                        <tr>
                                            <td>11/2</td>
                                            <td>48.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>4.05</td>
                                            <td>4.05</td>
                                            <td>5.41</td>
                                            <td></td>
                                            <td>5.41</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>7.25</td>
                                            <td>9.56</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>60.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>5.44</td>
                                            <td>5.44</td>
                                            <td>7.48</td>
                                            <td></td>
                                            <td>7.48</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>11.11</td>
                                            <td>13.44</td>
                                        </tr>
                                        <tr>
                                            <td>21/3</td>
                                            <td>73.0</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>8.63</td>
                                            <td>8.63</td>
                                            <td>11.41</td>
                                            <td></td>
                                            <td>11.41</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>14.92</td>
                                            <td>20.39</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>88.9</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>11.29</td>
                                            <td>11.29</td>
                                            <td>15.27</td>
                                            <td></td>
                                            <td>15.27</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>21.35</td>
                                            <td>27.68</td>
                                        </tr>
                                        <tr>
                                            <td>31/2</td>
                                            <td>101.6</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>13.57</td>
                                            <td>13.57</td>
                                            <td>18.63</td>
                                            <td></td>
                                            <td>18.63</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>-</td>
                                            <td>-</td>
                                        </tr>
                                        <tr>
                                            <td>4</td>
                                            <td>114.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>16.07</td>
                                            <td>16.07</td>
                                            <td>22.32</td>
                                            <td></td>
                                            <td>22.32</td>
                                            <td></td>
                                            <td>28.32</td>
                                            <td></td>
                                            <td>33.54</td>
                                            <td>41.03</td>
                                        </tr>
                                        <tr>
                                            <td>5</td>
                                            <td>141.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>21.77</td>
                                            <td>21.77</td>
                                            <td>30.97</td>
                                            <td></td>
                                            <td>30.97</td>
                                            <td></td>
                                            <td>40.28</td>
                                            <td></td>
                                            <td>49.11</td>
                                            <td>57.43</td>
                                        </tr>
                                        <tr>
                                            <td>6</td>
                                            <td>168.3</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>28.26</td>
                                            <td>28.26</td>
                                            <td>42.56</td>
                                            <td></td>
                                            <td>42.56</td>
                                            <td></td>
                                            <td>54.20</td>
                                            <td></td>
                                            <td>67.56</td>
                                            <td>79.22</td>
                                        </tr>
                                        <tr>
                                            <td>8</td>
                                            <td>219.1</td>
                                            <td></td>
                                            <td>33.31</td>
                                            <td>36.81</td>
                                            <td>42.55</td>
                                            <td>42.55</td>
                                            <td>64.64</td>
                                            <td>53.08</td>
                                            <td>64.64</td>
                                            <td>75.92</td>
                                            <td>90.44</td>
                                            <td>100.92</td>
                                            <td>111.27</td>
                                            <td>107.92</td>
                                        </tr>
                                        <tr>
                                            <td>10</td>
                                            <td>273.1</td>
                                            <td></td>
                                            <td>41.77</td>
                                            <td>51.03</td>
                                            <td>60.31</td>
                                            <td>60.31</td>
                                            <td>81.55</td>
                                            <td>81.55</td>
                                            <td>96.01</td>
                                            <td>114.75</td>
                                            <td>133.06</td>
                                            <td>155.15</td>
                                            <td>172.33</td>
                                            <td>155.15</td>
                                        </tr>
                                        <tr>
                                            <td>12</td>
                                            <td>323.9</td>
                                            <td></td>
                                            <td>49.73</td>
                                            <td>65.20</td>
                                            <td>73.88</td>
                                            <td>79.73</td>
                                            <td>97.46</td>
                                            <td>108.96</td>
                                            <td>132.08</td>
                                            <td>159.91</td>
                                            <td>186.97</td>
                                            <td>208.14</td>
                                            <td>238.76</td>
                                            <td>186.97</td>
                                        </tr>
                                        <tr>
                                            <td>14</td>
                                            <td>355.6</td>
                                            <td>54.69</td>
                                            <td>67.90</td>
                                            <td>81.33</td>
                                            <td>81.33</td>
                                            <td>94.55</td>
                                            <td>107.39</td>
                                            <td>126.71</td>
                                            <td>158.10</td>
                                            <td>194.96</td>
                                            <td>224.65</td>
                                            <td>253.56</td>
                                            <td>281.70</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>16</td>
                                            <td>406.4</td>
                                            <td>62.64</td>
                                            <td>77.83</td>
                                            <td>93.27</td>
                                            <td>93.27</td>
                                            <td>123.30</td>
                                            <td>123.30</td>
                                            <td>160.12</td>
                                            <td>203.53</td>
                                            <td>245.56</td>
                                            <td>286.64</td>
                                            <td>333.19</td>
                                            <td>365.35</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>18</td>
                                            <td>457.0</td>
                                            <td>70.57</td>
                                            <td>87.71</td>
                                            <td>122.38</td>
                                            <td>105.16</td>
                                            <td>155.80</td>
                                            <td>139.15</td>
                                            <td>205.74</td>
                                            <td>254.55</td>
                                            <td>309.62</td>
                                            <td>363.56</td>
                                            <td>408.26</td>
                                            <td>459.37</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>20</td>
                                            <td>508</td>
                                            <td>78.55</td>
                                            <td>117.15</td>
                                            <td>155.12</td>
                                            <td>117.15</td>
                                            <td>183.42</td>
                                            <td>155.12</td>
                                            <td>247.83</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>22</td>
                                            <td>559</td>
                                            <td>86.54</td>
                                            <td>129.13</td>
                                            <td>171.09</td>
                                            <td>129.13</td>
                                            <td>-</td>
                                            <td>171.09</td>
                                            <td>294.25</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>24</td>
                                            <td>610</td>
                                            <td>94.53</td>
                                            <td>141.12</td>
                                            <td>209.64</td>
                                            <td>141.12</td>
                                            <td>255.41</td>
                                            <td>187.06</td>
                                            <td>355.26</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>26</td>
                                            <td>660</td>
                                            <td>127.36</td>
                                            <td>202.72</td>
                                            <td>-</td>
                                            <td>152.87</td>
                                            <td>-</td>
                                            <td>202.72</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>28</td>
                                            <td>711</td>
                                            <td>137.32</td>
                                            <td>218.69</td>
                                            <td>271.21</td>
                                            <td>164.85</td>
                                            <td>-</td>
                                            <td>218.69</td>
                                            <td>-</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>30</td>
                                            <td>762</td>
                                            <td>147.28</td>
                                            <td>234.67</td>
                                            <td>292.18</td>
                                            <td>176.84</td>
                                            <td>-</td>
                                            <td>234.67</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>32</td>
                                            <td>813</td>
                                            <td>157.24</td>
                                            <td>250.64</td>
                                            <td>312.15</td>
                                            <td>188.82</td>
                                            <td>342.91</td>
                                            <td>250.64</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>34</td>
                                            <td>864</td>
                                            <td>167.20</td>
                                            <td>266.61</td>
                                            <td>332.12</td>
                                            <td>200.31</td>
                                            <td>364.90</td>
                                            <td>266.61</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>36</td>
                                            <td>914</td>
                                            <td>176.96</td>
                                            <td>282.27</td>
                                            <td>351.70</td>
                                            <td>212.56</td>
                                            <td>420.42</td>
                                            <td>282.27</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </>
    );
}

export default SeamlessPipe;